[context]
name = "scaffops"
version = "0.1.0"
url = "https://github.com/scaffops/scaffops"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
